// src/screen/CreateJobs/styles.ts
import {StyleSheet, Platform, StatusBar} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import Color from '../../theme/Colors';

const borderColor = '#ced4da';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Color.primaryBGColor,
  },
  container: {
    flexGrow: 1,
    backgroundColor: '#FFF',
  },

  formContainer: {
    backgroundColor: Color.white,
    padding: wp(4),
    borderRadius: wp(1),
    borderWidth: 1,
    borderColor: borderColor,
    flex: 1,
  },
  sectionTitle: {
    fontSize: hp(2.2),
    fontWeight: 'bold',
    color: Color.textColorSecondary,
    marginBottom: hp(1.5),
    borderBottomWidth: 1,
    borderBottomColor: borderColor,
    paddingBottom: hp(0.5),
  },
  inputGroup: {
    marginBottom: hp(2),
    justifyContent: 'center',
  },
  label: {
    marginLeft: wp('1%'),
    color: Color.black,
    fontSize: wp('4%'),
    marginBottom: 5,
  },
  required: {
    color: 'red',
  },
  input: {
    height: hp(6),
    borderWidth: 1,
    borderColor: borderColor,
    borderRadius: wp(1),
    paddingHorizontal: wp(3),
    fontSize: wp('3.5%'),
    backgroundColor: Color.white,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  multilineInput: {
    minHeight: hp(10),
    textAlignVertical: 'top',
  },
  dropdown: {
    height: hp(6),
    borderWidth: 1,
    borderColor: borderColor,
    borderRadius: wp(1),
    paddingHorizontal: wp(3),
    backgroundColor: Color.white,
    justifyContent: 'center',
  },
  buttonContainer: {
    marginTop: hp(2),
  },
  addressButton: {
    backgroundColor: Color.primaryBGColor,
    height: hp(4.5),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
  },
  addressButtonText: {
    color: Color.white,
    fontSize: hp(2),
    fontWeight: '600',
    marginLeft: wp(1),
  },
  saveButton: {
    backgroundColor: Color.primaryBGColor,
    height: hp(6),
    borderRadius: wp(10),
    marginBottom: hp(2),
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveButtonText: {
    color: Color.white,
    fontSize: hp(2.5),
    fontWeight: 'bold',
    marginLeft: wp(1),
  },
  cancelButton: {
    backgroundColor: Color.white,
    height: hp(6),
    borderRadius: wp(10),
    borderWidth: 1,
    borderColor: Color.primaryBGColor,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: {
    color: Color.textPrimaryColor,
    fontSize: hp(2.5),
    fontWeight: 'bold',
    marginLeft: wp(1),
  },
  errorText: {
    fontSize: hp(1.4),
    color: Color.errorTextColor,
    marginTop: hp(0.3),
  },
  noResultContainer: {
    marginTop: hp(1),
    alignItems: 'center',
    backgroundColor: Color.white,
    elevation: 5,
    flex: 1,
    justifyContent: 'center',
  },
  noResultCustomerSelectContainer: {

    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: hp(1),
    backgroundColor: Color.white,
    borderRadius: wp(1),
    padding: wp(4),
    borderWidth: 1,
    borderColor: borderColor,
  },
  noResultText: {
    fontSize: hp(2.5),
    color: Color.textColor,
    marginBottom: hp(1),
    paddingVertical: hp(2),
    fontWeight: '700',
    textAlign: 'center',
    fontStyle: 'italic',
  },

  addCustomerButtonContainer: {
    alignItems: 'center',
    // marginTop: hp(1), 
    paddingBottom: hp(2),

  },
  addCustomerButton: {
    backgroundColor: Color.primaryBGColor,
    paddingVertical: hp(1),
    paddingHorizontal: wp(3),
    width:wp(92),
    borderRadius: wp(1),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    
  },
  addCustomerButtonText: {
    color: Color.white,
    fontSize: hp(1.8),
    marginLeft: wp(1),
  },
  dropdownContainer: {
    backgroundColor: '#fff',
    maxHeight: hp(30),
    borderColor: '#ccc',
    borderWidth: 1,
    marginTop: 2,
    borderRadius: 5,
    zIndex: 10,
  },
  dropdownItem: {
    paddingHorizontal: wp(3),
    paddingVertical: hp(1.5),
    borderBottomColor: '#eee',
    borderBottomWidth: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexDirection: 'row',
  },
  round: {
    height: hp(4),
    width: hp(4),
    borderRadius: wp(8),
    borderWidth: 1,
    borderColor: '#000',
    alignItems: 'center',
    justifyContent: 'center',
  },
  line: {
    height: 1,
    backgroundColor: '#eee',
    marginVertical: hp(0.5),
  },
  dropdownText: {
    fontSize: wp(4),
    paddingLeft: 7,
    color: '#333',
  },
  selectCustomerOverlay: {
    position: 'absolute',
    top: hp(3.5),
    left: 0,
    right: 0,
    bottom: 0,
    height: hp(6),
    zIndex: 1,
  },
  clearSelectionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginTop: hp(1),
    paddingVertical: hp(0.8),
    paddingHorizontal: wp(2),
    borderRadius: 5,
    backgroundColor: '#ffe0e0',
    alignSelf: 'flex-start',
  },
  clearSelectionButtonText: {
    color: 'red',
    fontSize: wp(3.8),
    marginRight: wp(1),
  },
  noAddressResultContainer: {
    backgroundColor: Color.white,
    borderRadius: wp(1),
    padding: wp(4),
    marginTop: hp(1),
    alignItems: 'center',
    borderWidth: 1,
    borderColor: borderColor,
    flex: 1,
    justifyContent: 'center',
  },
  loadingText: {
    fontSize: wp(4.5),
    color: '#555',
    textAlign: 'center',
    marginTop: hp(5),
  },
  customerListContainer: {
    maxHeight: hp(50), 
    borderWidth: 0.5,
    borderColor: '#ccc',
    borderRadius: 6,
    backgroundColor: '#fff',
    marginTop: wp(1),
  },
  addressListContainer: {
    maxHeight: hp(30),
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 6,
    backgroundColor: '#fff',
    marginTop: 2,
  },
});

export default styles;