const Settings = {
    baseUrl: 'https://app.gascertificate.app/',
    api: 'https://app.gascertificate.app/',
    googleApiKey:'AIzaSyA2DLk-8F58uUCsgr5TihPQsOeid2arWr4',
       
    endpoints: {
      login: 'api/v1/login',
      signup: 'api/v1/register',
      otp_login: 'api/v1/login/send-otp',
      otp_login_validate: 'api/v1/login/otp-login',
      send_register_otp: 'api/v1/register/send-otp',
      validate_register_otp: 'api/v1/register/validate-otp',
      user_register: 'api/v1/register-new',   
      profile_update: 'api/v1/auth/profile/update',
      change_password: 'api/v1/auth/profile/update/password',
      draw_signature: 'api/v1/auth/profile/update/draw-signature',
      boiler_brands: 'api/v1/boiler-brands',
      boiler_brand_models: (id) =>  `api/v1/boiler-brand/${id}/manual`,
      file_signature: 'api/v1/auth/profile/update/file-signature',
      get_jobs_list: 'api/v1/jobs/list',
      get_customers_list: 'api/v1/customers',
      create_customers: 'api/v1/customer-store',
      customer_update: (id) =>  `api/v1/customer-update/${id}`,
      get_single_customer: (id) =>  `api/v1/customer/${id}`,
      customer_contact_info_update: (id) =>  `api/v1/customer-contact-info-update/${id}`,
      customer_job_address_update: (id) =>  `api/v1/customer-job-address/${id}/update`,
      customer_job_address_store: (id) =>  `api/v1/customer/${id}/job-addresses/store`,
      create_customers_address: 'api/v1/customer-property-store',
      create_customers_contact: 'api/v1/customer-contact-info-store',
      create_jobs: 'api/v1/jobs/store',
      job_update: (id) =>  `api/v1/job/update/${id}`,
      get_single_jobs:(id)=> `api/v1/job/${id}`,
      get_single_job_calendar:(id)=> `api/v1/job/calendar/${id}`,
      create_jobs_calendar: 'api/v1/job/calendar/store',
      create_service_record: 'api/v1/records/gas-service-record/store',
      get_customer_property: (id) => `api/v1/customer/${id}/property`,
      get_job_address: (id) => `api/v1/customer-job-address/${id}/job-addresses/list`,
      get_single_job_address: (id) => `api/v1/customer-job-address/${id}`,
      get_job_address_list: (id) => `api/v1/customer/${id}/job-addresses/list`,
      get_customar_job_list: (id) => `api/v1/customer/${id}/jobs/list`,
      get_signature: (id) => `api/v1/user/${id}/signature`,
      get_title: 'api/v1/titles',
      get_priorities: 'api/v1/customer/job/priorities',
      get_job_status: 'api/v1/job-status',
      get_calendar_time_slots: 'api/v1/calendar-time-slots?limit=24',
      get_records_list: 'api/v1/records-list',
      job_status_update:(id)=> `api/v1/customer/jobs/${id}/status-update`,

      get_quote_number: 'api/v1/quote-number',
      get_invoice_number: 'api/v1/invoice-number',
      store_quote:'api/v1/records/quote/store',
      store_invoice:'api/v1/records/invoice/store',
      quote_details_by_id:(id)=> `api/v1/records/quote/${id}/details`,
      quote_approve:(id)=> `api/v1/records/quote/${id}/approve`,
      quote_approve_email:(id)=> `api/v1/records/quote/${id}/approve-and-email`,
      get_vat_status:(id)=> `api/v1/vat-status/${id}`,
      get_link_job:(id,userId=0)=> `api/v1/records/jobs/${id}?user_id=${userId}`,
      invoice_details_by_id:(id)=> `api/v1/records/invoice/${id}/details`,
      invoice_approve:(id)=> `api/v1/records/invoice/${id}/approve`,
      invoice_approve_email:(id)=> `api/v1/records/invoice/${id}/approve-and-email`,
      company_user_update:(id)=> `api/v1/users/${id}/update`,
      company_user_list:(id)=> `api/v1/users/?user_id=${id}`,
      get_single_user:(id)=> `api/v1/user/${id}`,
      get_company_details:(id)=> `api/v1/company/${id}/details`,
      company_details_update:(id)=> `api/v1/company/${id}/update`,
      company_store: `api/v1/company`,
      company_user_store: `api/v1/users/store`,
      packages: `api/v1/pricing-packages`,
      get_status_slots: `api/v1/jobs/get-slot-status`,
      boiler_manual_download:(id)=> `api/v1/boiler-brand/download-manual/${id}`,
      cancel_reasons: `api/v1/cancel-reasons`,
      user_plan_details:(id)=> `api/v1/users/plans/${id}`,  
      cancel_job_submit:(jobId)=> `api/v1/customer/jobs/${jobId}/cancel-job`,  
      
     },
  
    version: {
      android: '1.0.0',
      ios: '1.0.0',
    },
  
    
  };
  export default Settings;